### ISSUE TITLE
Can you help update a version with pytorch example?

### ISSUE THREAD

**Issue by ntubertchen** [suinleelab/path_explain#4]
Hi there,

I was trying to reproduce the example and I found the current examples seems to be out of date with some incorrect path and it needs further modification.

On the other hand, although I've revise the current version and reproduce with TF version, I'm having a hard time reproducing the pytorch version. 

Can you help generating a pytorch version example?

Sincerely

**Comment by jjanizek** [comment]
Yes, definitely! I've been pretty busy with a couple of paper revisions the past month or so, but I can work on this again in about a week!

**Comment by shubhe25p** [comment]
I have created a PyTorch example. Can you review it?

**Comment by psturmfels** [comment]
Closing this issue. If you have more specific pytorch questions please open a new issue.
