### ISSUE TITLE
Unable to use multiprocessing pool with PathExplainerTF

### ISSUE THREAD

**Issue by astrogilda** [suinleelab/path_explain#6]
When I do the following, I get an error that tensorflow objects are not pickleable:

import multiprocessing as mp

explainer = PathExplainerTF(model)

with mp.Pool() as p:
    attributions = p.starmap(explainer.attributions, [i, ...] for i in x_test])

**Comment by psturmfels** [comment]
I'm not sure why I didn't respond to this earlier, but in general deep-learning frameworks aren't super multi-processing friendly. They already batch parallelize much of the computation on the back-end, so there is very little reason to ever explicitly open multiple threads when doing deep learning.

For example, in your code, it would be much better to simply write:
attributions = explainer.attributions(x_test)

**Comment by psturmfels** [comment]
I'm not sure why I didn't respond to this earlier, but in general deep-learning frameworks aren't super multi-processing friendly. They already batch parallelize much of the computation on the back-end, so there is very little reason to ever explicitly open multiple threads when doing deep learning.

For example, in your code, it would be much better to simply write:
attributions = explainer.attributions(x_test)
