### ISSUE TITLE
cannot import name 'EmbeddingExplainerTF'

### ISSUE THREAD

**Issue by jackashore** [suinleelab/path_explain#7]
Hi, I installed `path-explain` via `pip` and somehow cannot import `EmbeddingExplainerTF` class, although I have no trouble importing `PathExplainerTF`

```
from path_explain import EmbeddingExplainerTF
```

**Comment by jjanizek** [comment]
Hi -- what error do you get when you try to import the Embedding Explainer?

**Comment by jackashore** [comment]
This one:

`ImportError: cannot import name 'EmbeddingExplainerTF'`

**Comment by jumelet** [comment]
I had the same issue, the reason for this is that [\_\_init\_\_.py](https://github.com/suinleelab/path_explain/blob/master/path_explain/__init__.py) of `path_explain` does not contain the explicit import to `EmbeddingExplainerTF`.

If you add the following line to this file it should work:
`from .explainers.embedding_explainer_tf import EmbeddingExplainerTF`

I also had to alter line 7 of [embedding\_explainer\_tf.py](https://github.com/suinleelab/path_explain/blob/master/path_explain/explainers/embedding_explainer_tf.py) to the following, to prevent circular imports:
`from .path_explainer_tf import PathExplainerTF`

**Comment by jjanizek** [comment]
Thank you for catching this!! Would you want to submit a pull request with these two line changes? Otherwise I will fix this ASAP

**Comment by jjanizek** [comment]
Ok, I also just realized that the pip installation is out of date 😅, I'll have to update that this week as well

**Comment by neelbhandari6** [comment]
I faced the same issue with  EmbeddingExplainerTF. 
I have pip installed path-explain, and my execution is currently on Google Colab.
My error:

ImportError                               Traceback (most recent call last)

<ipython-input-30-b0853a661a3d> in <module>()
      2 
      3 # This is a custom explainer to explain huggingface models
----> 4 from path_explain import EmbeddingExplainerTF, text_plot, matrix_interaction_plot, bar_interaction_plot
      5 
      6 tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

ImportError: cannot import name 'EmbeddingExplainerTF' from 'path_explain' (/usr/local/lib/python3.7/dist-packages/path_explain/__init__.py)

**Comment by jjanizek** [comment]
Ok, I believe this should be fixed with the latest version of the package in PyPi (version 0.0.7)!

**Comment by psturmfels** [comment]
Closing this now! Re-open if this is still an issue.
